### ISSUE TITLE
missing pip

### ISSUE THREAD

**Issue by statkclee** [kleinee/jns#1]
I could not install jupyter becasue of pip pakcage manager omitted.

You might need to add 'sudo apt-get install python-pip' somewhere.

**Comment by kleinee** [comment]
Dear Kwangchun,

Take a look at install_python.sh

Python 3.5.0 comes bundled with pip. it shows up as pip3 in /usr/local/bin/. That is the reason why I created a soft link to make pip3 the default: 

ln -s /usr/local/bin/pip3 pip. 

Best Regards & Thanks for your feedback. 

Eckhard

**Comment by kleinee** [comment]
https://pip.pypa.io/en/latest/installing/ <https://pip.pypa.io/en/latest/installing/> Python 2.7.9 and later (on the python2 series), and Python 3.4 and later include pip by default.

**Comment by kleinee** [comment]
corrected soft link in README and script

ln -s /usr/local/bin/pip3 /usr/local/bin/pip
