### ISSUE TITLE
blas before scipy

### ISSUE THREAD

**Issue by grfiv** [kleinee/jns#12]
I found that having
```
apt-get -y install libblas-dev liblapack-dev
apt-get -y install libatlas-base-dev gfortran
```
**after** `scipy` and `numpy` installation caused an exception, So I installed them first and things were fine.

Otherwise I found this repo very helpful and I thank you for it.

**Comment by kleinee** [comment]
I updated the installation order in '''install_stack.sh''' so that others do not run into the exception you encountered during installation. Thanks for your valuable feedback!
