### ISSUE TITLE
possible issue when install conf_jupyter.sh

### ISSUE THREAD

**Issue by gusdrawn** [kleinee/jns#16]
I get this error.
`pi@raspberrypi:~/jns$ sudo -u pi ./conf_jupyter.sh
Writing default config to: /home/pi/.jupyter/jupyter_notebook_config.py
Installing IPython kernel spec
Enabling: jupyterlab
- Writing config: /home/pi/.jupyter
    - Validating...
      jupyterlab  OK
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
Enabling notebook extension bqplot/extension...
      - Validating: OK
Enabling IPython clusters tab
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 38002  100 38002    0     0  33832      0  0:00:01  0:00:01 --:--:-- 33832
n-install: ERROR:
  Aborting, because n and/or Node.js-related binaries are already
  in the $PATH:
           
         /usr/bin/node
  
  Please remove any existing n, Node.js installation, then try 
  again.
  

Errored, use --debug for full output:
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

Errored, use --debug for full output:
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

Errored, use --debug for full output:
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.`

**Comment by kleinee** [comment]
Thanks ***gusdrawn*** for raising this issue. I verified your findings with a fresh install.  https://github.com/mklement0/n-install states: Before you can use ```n``` and any installed Node.js versions, you must open a new terminal tab/window or reload your shell initialization file. I got that wrong in  the original configuration script. However the suggested solution mentioned on the website above does NOT work either:

```bash    
set -i           # turn on interactive mode
 . ~/.basic   # reload (source) the initialization file
set +i          # turn interactive mode back off
```

The workaround that I came up with to execute a separate shell script that installs ```node```. I do not claim that this is elegant but it works. If you have a more elegant solution please drop me a line.
