### ISSUE TITLE
How to start the server when raspi boots?

### ISSUE THREAD

**Issue by royerloic** [kleinee/jns#17]
How to start the server when raspi boots? Crontab?

**Comment by kleinee** [comment]
Create a script called ```jupyter_start.sh``` in ```\home\pi``` with the following content

```bash
#/bin/bash
. /home/pi/.venv/jns/bin/activate
jupyter lab
```
Replace  ```jupyter lab``` with ```jupyter notebook``` if you want to start with the notebook interface instead. 

Save the file and make it executable with ```sudo chmod +x ./jupyter_start.sh```.

Open ```/etc/rc.local``` with your editor of choice and  add ```sudo -u pi /home/pi/jupyter_start/sh"```. Save the file and reboot. After reboot you should be able to access the server without logging in.
