### ISSUE TITLE
requirements.txt : sqlite3-kernel fails

### ISSUE THREAD

**Issue by mt08xx** [kleinee/jns#25]
requirements.txt : sqlite3-kernel fails

During `inst_stack.sh`, it fails to install `qlite3-kernel`

- Log
```
...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting sqlite3-kernel==1.0
  Could not find a version that satisfies the requirement sqlite3-kernel==1.0 (from versions: )
No matching distribution found for sqlite3-kernel==1.0
...
```

It may need to be installed manually with `sqlite3` package.

```
sudo apt install -y sqlite3 
source /home/pi/.venv/jns/bin/activate
git clone https://github.com/brownan/sqlite3-kernel
cd sqlite3-kernel
python3 setup.py install
python3 -m sqlite3_kernel.install
```

Or remove the line from `requirements.txt`.

**Comment by kleinee** [comment]
Thanks @mt08xx - I installed the kernel for a test and simply forgot to remove it from requirements.txt.  Since the kernel might not be of general interest I'll remove it.

**Comment by kleinee** [comment]
Rather than removing the rebel from requirements.txt I made installation an option.
