### ISSUE TITLE
Jupyter Lab not working with tornado==6.0 or tornado==6.0.1

### ISSUE THREAD

**Issue by Kevin--R** [kleinee/jns#32]
Not working since I updated my installation last weekend.

Tried a fresh install last weekend and again yesterday - still would not work.

Able to connect to notebook but cells will not execute.

Looking at jupyter log noticed warnings about "Replacing stale connection":

`[W 18:29:26.810 LabApp] Replacing stale connection: c8acf0ae-d519-4346-8404-9b5eba47b0a7:fd93f7ae-9a0f-4a41-a0a0-747be357341d`

Searching the web, I found others reporting the same or similar problems caused by updating to tornado version 6+.

[tornado 6.0 breaks notebook #4439](https://github.com/jupyter/notebook/issues/4439)

Downgrading to tornado==5.1.1 fixed problems for me.

**Comment by kleinee** [comment]
Thanks for reporting this issue @Kevin--R! As you can see I downgraded tornado as you suggested as it works at my end as well. Should have tested after updating the requirements... Took the liberty to fix the url in your bug report above.

Eckhard

**Comment by kleinee** [comment]
@Kevin--R : the combination of pyzmq==17.1.3  and tornado==6.0.1 seems to work giving the impression that pyzmq caused the issue. Can you try at your end to confirm" - Thanks Eckhard

**Comment by Kevin--R** [comment]
@kleinee I tried pyzmq==17.1.3 and tornado==6.0.1 as you suggested, and my problems returned (cells in notebooks not executing).

I switched back and fourth a couple of times to confirm and I've gone back to  pyzmq==18.0.1 and tornado==5.1.1

-Kevin

**Comment by Kevin--R** [comment]
@kleinee another update:

after my last post, I ran `pip3 list --outdated` and got the following result:

```
Package           Version Latest  Type 
----------------- ------- ------- -----
jupyterlab-server 0.2.0   0.3.0   wheel
netCDF4           1.4.2   1.4.3.1 sdist
notebook          5.7.4   5.7.5   wheel
psutil            5.5.1   5.6.0   sdist
setuptools        33.1.1  40.8.0  wheel
SQLAlchemy        1.2.18  1.3.0   sdist
tensorboard       1.13.0  1.13.1  wheel
tldextract        2.2.0   2.2.1   wheel
tornado           5.1.1   6.0.1   sdist
vega              1.4.0   2.0.0   wheel
```

I updated all to latest versions.

netCDF4 failed to update (Failed building wheel for netCDF4).

Then I downgraded to jupyterlab-server==0.2.0 because `pip3 check` produced this output:
```
jupyterlab 0.35.4 has requirement jupyterlab-server<0.3.0,>=0.2.0, but you have jupyterlab-server 0.3.0.
```

`pip3 list --outdated` now produces this output:
```
Package           Version Latest  Type 
----------------- ------- ------- -----
jupyterlab-server 0.2.0   0.3.0   wheel
netCDF4           1.4.2   1.4.3.1 sdist
```

Jupyter Lab now seems to be working as expected - I didn't test extensively but the problem with notebook cells not executing is resolved.

-Kevin

**Comment by kleinee** [comment]
Thanks for swiftly reporting your test results @Kevin--R,

I will push updated requirements shortly. Cannot build netCDF4 version 1.4.3.1 at my end either as I get the error netCDF4/_netCDF4.pyx:1203:0: 'membuf.pyx' not found.

As far as vega goes I will stick with vega version .4.0 as version 2.0.0 works in lab but NOT in the older notebook interface that some might still be using (see last issue).

As such I settle for:
```
Package           Version Latest  Type 
----------------- ------- ------- -----
jupyterlab-server 0.2.0   0.3.0   wheel
netCDF4           1.4.3   1.4.3.1 sdist
vega              1.4.0   2.0.0   wheel
```

-Eckhard
