### ISSUE TITLE
Instructions for installing the R kernel

### ISSUE THREAD

**Issue by HarvsG** [kleinee/jns#35]
Please add instructions or a script for installing the R kernel if possible/feasible

**Comment by kleinee** [comment]
George (@HarvsG),

I assume that you successfully executed the scripts in this repository and ended up with a working ```jupyter lab``` installation. If you further have R installed, you can add the ```irtkernel``` following the instructions in [this link](https://irkernel.github.io/installation/):

1. Open a terminal and activate the virtual environment: ```. ~/.venv/jns/bin/activate```
2. Start `R` from the command line
3. At the prompt execute:

```R
install.packages('IRkernel')
IRkernel::installspec()
```

If all goes to plan you can reboot the pi and should be able to use the ```irkernel```
Hope that this works for you. 

PS: I am working on a script that builds ```R```  from source and adds the ```irkernel```. I will add it to this repository once I am done.


Best Regards

Eckhard

**Comment by kleinee** [comment]
HI @HarvsG,

Did you try my suggestion above? If it works at your end I can close this issue.

Thanks & Regards

Eckhard

**Comment by rggefrm** [comment]
Dear Echerhard,
you can close the issue.
I can confirm, your suggested code worked for me.
Raspberry and pixel chromebook in crouton
I will now install it also on my zero

Frank
