### ISSUE TITLE
how to install julia kernel with latest julia (1.1) already installed

### ISSUE THREAD

**Issue by rggefrm** [kleinee/jns#36]
The raspberry julia is old (0.6). The binaries from the julia site works on the raspberry without problems, so I have installed version 1.1
Does anyone know how to use the script so I can use my local julia installation?

**Comment by kleinee** [comment]
Hi @rggefrm, 

I also installed 1.1 and think it is a lot better but 
I assume that you you already have jupyter working on the Pi and that if you type ```Julia``` and hit enter, you start 1.1 rather than 0.6.

Activate the environment by running ```./venv/jns/bin/activate``` and then execute:

```bash
julia -e 'using Pkg; Pkg.add("IJulia");'
julia -e 'using IJulia;'
```

The trick is ```using Pkg``` in the snippet above as Julia has changed the package management.  I have not upgraded to 1.1 because - to my knowledge - the binary on the julia site do not run on the lower end Pis. Other than that I agree that 1.1 is far more stable than 0.6.

Hope this works for you. If it does, please let me know so that I can close this issue.

Best Regards

Eckhard

**Comment by rggefrm** [comment]
Dear Eckhard,

many thanks for your help. I will try out when I come home from work. Yes I
have jupyter running thanks to the excellent guide / scripts.
I have attached a M2 SSD and jupyter lab runs very well in this setting.

Best Wishes

Frank
PS: On other thing I noticed, there was a warning that pip is 9.0 and I
shall use version 19.


Am Fr., 17. Mai 2019 um 18:01 Uhr schrieb Eckhard Kleine <
notifications@github.com>:

**Comment by kleinee** [comment]
Hi Frank (@rggefrm)

Had a typo in my last comment which is now corrected. Did you get it to work?

Eckhard

**Comment by rggefrm** [comment]
Hi Eckhard,

I have installed the julia kernel this afternoon, most likely after you
have made the correction. Works nicely!
The commands you suggested to install the Rkernel works also with R 3.6.0
compiled from source. I will now try (again) to compile Rstudio server.

Best Wishes

Frank

Am Sa., 18. Mai 2019 um 16:40 Uhr schrieb Eckhard Kleine <
notifications@github.com>:

**Comment by kleinee** [comment]
Hi Frank,

Glad to hear that it worked. I am still thinking about a sensible approach to upgrading Julia  for all Pi models as the official binaries of version 1.0.4 only support ARMv7. So for the lower end Pi models we seem to be out of luck without building from source.

Eckhard

**Comment by rggefrm** [comment]
Dear Eckhard,
could you add the julia 1.1.1 installation and R how To to your README file?

Just a suggestion

Frank

**Comment by kleinee** [comment]
Hi Frank,

I have prepared scripts for R-3.6.0 and Juila-1.1.0 and can hopefully add them to the repository shortly.    Not sure about Julia-1.1.1. How did you install?

Eckhard

**Comment by kleinee** [comment]
Hi Frank,
The installer scripts for R-3.6.0 and Julia-1.1.0 are online. I still have to test the Julia installer on a Raspberry Pi Zero but by all odds it should work.

Regards
Eckhard

**Comment by rggefrm** [comment]
Dear Eckhard,

you saved my day ☺
I had compiled R 3.6 on the model 3B and thought I could just transfer the
files over to pi zero. Of course, it didn't work (because of dependencies
failures). I had plans to compile R on the zero tonight.
Did you know there is a git (with binaries) for RStudio for the raspberry.
https://github.com/ArturKlauser/raspberrypi-rstudio/releases

Successfully installed on the 3B model (rstudio requires libssl1.02 which I
had to install manually). I didn't have the time to try on the zero.

Best Wishes

Frank


Am Sa., 1. Juni 2019 um 11:54 Uhr schrieb Eckhard Kleine <
notifications@github.com>:
