### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by HarvsG** [kleinee/jns#49]
With python 3.5 reaching EoL in Jan 2021 will jns be transitioning to python 3.6 and how might we upgrade out installs?

**Comment by kleinee** [comment]
Hi @HarvsG, sorry fr the late reply. Teh repository really deserves an update. Problem is time and the pace at which things are moving on all fronts: Raspberry Pi, Python and of course Jupyter. I am currently using  the [latest Pi Os](https://downloads.raspberrypi.org/raspios_full_armhf_latest) build on a Raspberry Pi 4 with 4 GB of memory and it works fine. The latest Python version supported by piwheels is 3.7.3 and things run just fine. I had to run ```export NODE_OPTIONS=--max_old_space_size=2048``` to make ```jupyter lab build``` work even on this Pi version. I did not recently try to install on any other Pi. Perhaps things have changed in the meantime but the javascript underpinnings really are memory intensive. For Julia take a look at [jlcross](https://github.com/Julia-Embedded/jlcross) on GitHub.  Hope that helps. Stay Safe!
