### ISSUE TITLE
QUestion with a armv7l laptop 

### ISSUE THREAD

**Issue by Rodartist** [kleinee/jns#8]
I installed the scripts in which I had jupyter from a previous installed and I'mm looking to run jupyter notebook. 

I maybe should have uninstalled the miniconda ... and all the other things before installing this github scripts.... but anyways I could try again also unless I find a resolve to get jupyter notebook going...

Am I missing the command only or is it missing from my path cause its the previous install path?

jupyter: 'notebook' is not a Jupyter command

any help is appreciated
this is a chromebook running slackware. And I'm loking to have jupyter notebook going as to start practicing with the languages beginner

**Comment by kleinee** [comment]
My scripts were originally intended to be used on a Raspberry Pi. I never used slackware / chrome books and hence cannot comment. From a quick search on Goggle I can only imagine that this takes some tweaking.

The command to start the server is ```jupyter notebook```.  Please report back if you succeed as it might be interesting to others. 

Best Regards & Best of Luck

Eckhard

**Comment by kleinee** [comment]
Had no further feedback on this issue that isn't related to the intended platform.
